FROM node:carbon

ENV HABIDAT_DOMAIN
ENV HABIDAT_USER_SUBDOMAIN
ENV HABIDAT_USER_SMTP_HOST
ENV HABIDAT_USER_SMTP_PORT
ENV HABIDAT_USER_LDAP_HOST
ENV HABIDAT_USER_LDAP_PORT
ENV HABIDAT_USER_LDAP_BINDDN
ENV HABIDAT_USER_LDAP_BASE
ENV HABIDAT_USER_LDAP_PASSWORD
ENV HABIDAT_DISCOURSE_API_URL
ENV HABIDAT_DISCOURSE_API_KEY
ENV HABIDAT_DISCOURSE_API_USERNAME
ENV HABIDAT_USER_NEXTCLOUD_DB_HOST
ENV HABIDAT_USER_NEXTCLOUD_DB_PORT
ENV HABIDAT_USER_NEXTCLOUD_DB_DATABASE
ENV HABIDAT_USER_NEXTCLOUD_DB_USER
ENV HABIDAT_USER_NEXTCLOUD_DB_PASSWORD

ADD . /habidat-user

WORKDIR /habidat-user

RUN npm install && npm install pm2 -g

RUN \
  apt-get update \
  && apt-get -y install gettext-base \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

ENTRYPOINT entrypoint.sh

CMD pm2-docker start app.js 
