FROM node:carbon

ARG HABIDAT_DOMAIN
ARG HABIDAT_USER_SUBDOMAIN
ARG HABIDAT_USER_SMTP_HOST
ARG HABIDAT_USER_SMTP_PORT
ARG HABIDAT_USER_LDAP_HOST
ARG HABIDAT_USER_LDAP_PORT
ARG HABIDAT_USER_LDAP_BINDDN
ARG HABIDAT_USER_LDAP_BASE
ARG HABIDAT_USER_LDAP_PASSWORD
ARG HABIDAT_DISCOURSE_API_URL⁼http
ARG HABIDAT_DISCOURSE_API_KEY
ARG HABIDAT_DISCOURSE_API_USERNAME
ARG HABIDAT_USER_NEXTCLOUD_DB_HOST
ARG HABIDAT_USER_NEXTCLOUD_DB_PORT
ARG HABIDAT_USER_NEXTCLOUD_DB_DATABASE
ARG HABIDAT_USER_NEXTCLOUD_DB_USER
ARG HABIDAT_USER_NEXTCLOUD_DB_PASSWORD

RUN git clone https://github.com/soudis/habidat-user.git
WORKDIR /habidat-user
RUN npm install
RUN npm install pm2 -g

RUN \
  apt-get update \
  && apt-get -y install gettext-base \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

RUN envsubst < config/config.json.sample > config/config.json

VOLUME /habidat-user/config

CMD pm2-docker start app.js 
